"""Constants for HomeWizard Energy."""

SUPPORTED_API_VERSION = "v1"

SUPPORTS_STATE = ["HWE-SKT"]
SUPPORTS_IDENTIFY = ["HWE-SKT", "HWE-P1"]
SUPPORTS_SYSTEM = ["HWE-SKT", "HWE-P1", "SDM230-WIFI", "SDM630-WIFI"]
SUPPORTS_DECRYPTION = ["HWE-P1"]

LATEST_STABLE_FIRMWARE = {
    "HWE-P1": "4.18",
    "HWE-SKT": "3.03",
    "HWE-WTR": "2.03",
    "SDM230-WIFI": "3.06",
    "SDM630-WIFI": "3.06",
}
